FROM quay.io/keycloak/keycloak:26.2.4 as builder

ARG KEYCLOAK_CONF_FILE=conf/infra/keycloak.conf
ARG KEYCLOAK_DEFAULT_REALMS=/realms/gateway_api.json

ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

WORKDIR /opt/keycloak

COPY ${KEYCLOAK_CONF_FILE} /opt/keycloak/conf/
COPY keystore/infra/nano_keycloak_key.keystore /opt/keycloak/conf/
COPY ${KEYCLOAK_DEFAULT_REALMS} /opt/keycloak/import/

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:26.2.4

COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["sh", "-c", "/opt/keycloak/bin/kc.sh import --file /opt/keycloak/import/gateway_api.json && /opt/keycloak/bin/kc.sh start --optimized"]
