services:
  simple_api_build:
    build:
      context: simple_api/
    image: simple_api  # 建立共用的映像檔

  simple_api_1:
    image: simple_api  # 直接使用建好的映像檔
    container_name: simple_api_1
    ports:
      - "8081:8080"
    environment:
      - QUARKUS_HTTP_PORT=8080
    depends_on:
      - simple_api_build

  simple_api_2:
    image: simple_api
    container_name: simple_api_2
    ports:
      - "8082:8080"
    environment:
      - QUARKUS_HTTP_PORT=8080
    depends_on:
      - simple_api_build

  simple_api_3:
    image: simple_api
    container_name: simple_api_3
    ports:
      - "8083:8080"
    environment:
      - QUARKUS_HTTP_PORT=8080
    depends_on:
      - simple_api_build

#  routing_api:
#    image: routing_api
#    container_name: routing_api
#    build:
#      context: ./quarkus/routing_api
#    ports:
#      - "8080:8080"
#    environment:
#      - QUARKUS_HTTP_PORT=8080
#      - SIMPLE_API_INSTANCES=http://simple_api_1:8080,http://simple_api_2:8080,http://simple_api_3:8080
#    depends_on:
#      - simple_api_1
#      - simple_api_2
#      - simple_api_3
