services:
  simple_api_build:
    build:
      context: simple-api/
    image: simple_api

  routing_api_build:
    build:
      context: routing-api/
    image: routing_api

  simple_api_1:
    image: simple_api
    container_name: simple_api_1
    ports:
      - "${SIMPLE_API_1_PORT}:8080"
    environment:
      - QUARKUS_HTTP_PORT=8080
    depends_on:
      - simple_api_build

  simple_api_2:
    image: simple_api
    container_name: simple_api_2
    ports:
      - "${SIMPLE_API_2_PORT}:8080"
    environment:
      - QUARKUS_HTTP_PORT=8080
    depends_on:
      - simple_api_build

  simple_api_3:
    image: simple_api
    container_name: simple_api_3
    ports:
      - "${SIMPLE_API_3_PORT}:8080"
    environment:
      - QUARKUS_HTTP_PORT=8080
    depends_on:
      - simple_api_build

#  routing_api:
#    image: routing_api
#    container_name: routing_api
#    ports:
#      - "8080:8080"
#      - "5005:5005"
#    environment:
#      - QUARKUS_HTTP_PORT=8080
#      - SIMPLE_API_INSTANCES=http://simple_api_1:8080,http://simple_api_2:8080,http://simple_api_3:8080
#    depends_on:
#      - simple_api_1
#      - simple_api_2
#      - simple_api_3
#      - routing_api_build
