FROM postgres:15

#ARG POSTGRESQL_CONF_FILE=/conf/postgresql.conf
#
#COPY ${POSTGRESQL_CONF_FILE} /etc/postgresql/postgresql.conf
#
#COPY script/10-postgresql-config.sh /docker-entrypoint-initdb.d/
#RUN chmod +x /docker-entrypoint-initdb.d/10-postgresql-config.sh

CMD ["postgres"]
