services:
  nano_postgresql:
      build:
        context: "${CONTEXT_PATH_POSTGRESQL}"
#        args:
#          POSTGRESQL_CONF_FILE: "${POSTGRESQL_CONF_FILE}"
      image: nano_postgresql
      restart: always
      volumes:
        - "${POSTGRES_DATA_PATH}:/var/lib/postgresql/data"
        - "${INIT_SQL_PATH}:/docker-entrypoint-initdb.d/0.sql"
      ports:
        - "${POSTGRESQL_PORT}:${INTERNAL_POSTGRESQL_PORT}"
      environment:
        - "POSTGRES_DB=${POSTGRES_DB}"
        - "POSTGRES_USER=${POSTGRES_USER}"
        - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      healthcheck:
        test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
        interval: 5s
        timeout: 5s
        retries: 3
