apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
        - name: simple-api
          image: nekowandrer/simple_api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_HTTP_PORT
              value: "8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-api
  template:
    metadata:
      labels:
        app: gateway-api
    spec:
      containers:
        - name: gateway-api
          image: nekowandrer/gateway_api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 5005
          env:
            - name: QUARKUS_HTTP_PORT
              value: "8080"
            - name: AVAILABLE_API_INSTANCES
              value: "http://simple-api-service:8080"
