apiVersion: v1
kind: Service
metadata:
  name: simple-api-service
spec:
  selector:
    app: simple-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: default-protocol
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: routing-api-service
spec:
  selector:
    app: routing-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: default-protocol
  type: NodePort
